apiVersion: v1
kind: ConfigMap
metadata:
  name: config-yml
  namespace: web-content-analysis
data:
  config.yml: |
sparkConfiguration :
  configs :
    - key : spark.app.name
      value : cassandra migrator
    - key : spark.master
      value : spark://10.10.5.30:32650
    - key : spark.submit.deployMode
      value : cluster

sourceProps :
   formats :
     - value : org.apache.spark.sql.cassandra

   options :
     - key : spark.cassandra.connection.host
       value : 10.10.5.20
     - key : spark.cassandra.connection.port
       value : 8125
     - key : spark.cassandra.auth.username
       value : cassandra
     - key : spark.cassandra.auth.password
       value : cassandra
     - key : spark.cassandra.connection.ssl.keyStore.path
       value : /opt/nn1-server-keystore.jks
     - key : spark.cassandra.connection.ssl.keyStore.password
       value : cassandra
     - key : spark.cassandra.connection.ssl.trustStore.path
       value : /opt/generic-server-truststore.jks
     - key : spark.cassandra.connection.ssl.trustStore.password
       value : cassandra
     - key : keyspace
       value : bigmart
     - key : table
       value: v_site
     - key : spark.cassandra.connection.ssl.clientAuth.enabled
       value : true
     - key: spark.cassandra.connection.ssl.enabled
       value: true
     - key: spark.cassandra.input.consistency.level
       value: ALL
     - key: spark.cassandra.output.consistency.level
       value: ALL
     - key: spark.cassandra.read.timeoutMS
       value: 240000

sinkProps :
  formats:
    - value: org.apache.spark.sql.cassandra
  modes:
    - value: append
  options:
    - key: spark.cassandra.connection.host
      value: 146.190.6.111
    - key: spark.cassandra.connection.port
      value: 32001
    - key: spark.cassandra.auth.username
      value: cassandra
    - key: spark.cassandra.auth.password
      value: cassandra
      # - key: spark.cassandra.connection.ssl.keyStore.path
      #   value: /home/samir/Desktop/Cassandra/nn1-server-keystore.jks
      # - key: spark.cassandra.connection.ssl.keyStore.password
      #   value: cassandra
      # - key: spark.cassandra.connection.ssl.trustStore.path
      #   value: /home/samir/Desktop/Cassandra/generic-server-truststore.jks
      # - key: spark.cassandra.connection.ssl.trustStore.password
      # value: cassandra
    - key: keyspace
      value: bigmart
    - key: table
      value: v_site
      # - key: spark.cassandra.connection.ssl.clientAuth.enabled
      # value: true
      # - key: spark.cassandra.connection.ssl.enabled
      # value: true